# Generated by Django 4.2.20 on 2026-03-15 02:47

from django.db import migrations


def create_default_users(apps, schema_editor):
    User = apps.get_model('locker_system', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(username='admin', email='admin@example.com', password='admin123', role='admin')
    if not User.objects.filter(username='user').exists():
        User.objects.create_user(username='user', email='user@example.com', password='user123', role='user')


def delete_default_users(apps, schema_editor):
    User = apps.get_model('locker_system', 'User')
    User.objects.filter(username__in=['admin', 'user']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('locker_system', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users, delete_default_users),
    ]
